version: '3'

services:
  search-front:
    image: node:16-alpine
    container_name: search-front
    tty: true
    stdin_open: true
    command: npm start
    restart: on-failure
    working_dir: /app
    volumes:
      - ./front:/app
    environment:
      - REACT_APP_API_ADDRESS=http://localhost:3001/
    depends_on:
      - search-back
    ports:
      - 3000:3000

  search-back:
    image: node:16
    container_name: search-back
    restart: on-failure
    tty: true
    stdin_open: true
    working_dir: /app
    ports:
      - 3001:3001
    volumes:
      - ./back:/app
    depends_on:
      - search-database
    environment:
      - MONGO_URI=mongodb://search-database:27017/products

  search-database:
    image: mongo
    container_name: search-database
    restart: on-failure
    ports:
      - 27017:27017
